### PR TITLE
Nav updates

### PR DESCRIPTION
**Pull request by awolfe76**
#### The has several PRs that go with it and should be merged AFTER others.

---

Adds in links to tools and data publication for logged out users.

Adjusts logged in navigation by moving "Home" to the left of the user ...

nav

### CODE REVIEW

**Comment by wpears** [comment]
Seems to me like we'd want to always display the data-publication and tools links in the header. I don't think it's intuitive that you'd need to log out in order to get those nav options.

**Review by wpears — CHANGES_REQUESTED** [review]
*(see above)*

**Comment by awolfe76** [comment]
I definitely see what you mean here.

The goal was to make the platform, the app, be outside of the rest of the site. We can, and need to, do a little more to make sure this separation is a bit more clear. Things like:

- a little bit different styling,
- maybe make the app link open a new window, and
- possibly a few others.

There are other updates coming to the home page to call out other parts of the site, as well as the platform.

@designlanguage @keileyo @colleenms

**Comment by designlanguage** [comment]
@wpears - There will be a lot of content on the home page accessible to the public (non-filers) that doesn't have anything to do with logging into the platform, so having the tools/resources as pages within the platform nav doesn't seem accurate.

It gets tricky with what the header looks like as well. Would the main text in the header always say "FFIEC HMDA Platform"? If so, that could be confusing for non-filers.

To help the user understand where they are, I recommend differentiating the homepage header from the platform. I also don't think a filer would need to log out to access other resources. When they select the platform from the homepage, it could open a new tab/window into the app. The platform is complex enough with the step navigation, and it'll only get more complex with multiple years being introduced, so I think we should keep it simple and keep the app separate from the homepage.

Here's what I'm recommending: https://github.com/cfpb/hmda-platform-ui/issues/1025

If there are benefits I'm not considering, let's take time today to discuss.

**Review by wpears — APPROVED** [review]
Approved as a stopgap for 4/1 before https://github.com/cfpb/hmda-platform-ui/issues/1025#issuecomment-371968362 :+1:

**Pull request merged**
