### PR TITLE
Prev filename bug

### LINKED ISSUE #728: Filename exists on first filing
After I rebuilt the local setup, registered an account, logged in, and clicked begin filing I saw this 

filename.

Notice the filename, but I hadn't done anything yet. This was the first time through.

### PR DESCRIPTION
**Pull request by wpears**
Closes #728

### CODE REVIEW

**Comment by awolfe76** [comment]
@wpears I had the same thought as [you did here](https://github.com/cfpb/hmda-platform-ui/issues/728#issuecomment-324464059) but I think it could be a little bigger than that.

If you have multiple filers from the same institution doing things (leaving, coming back, reuploading) it's possible that filename won't be correct since we're using `localStorage` here.

We may need to hit the `summary` endpoint to get the filename based on part of the `state`?

**Comment by wpears** [comment]
File names aren't going server-side at all, so unless we change the API and make the filename part of the upload POST (a header like X-HMDA-Filename) that gets associated with a submission, this is the best we can do.

We'd still run into an issue if:
 - User A uploads
 - User B refiles
 - User A returns and sees "`name_of_first_file.txt` in progress" on the upload page, if they venture there.

This is pretty edge-casey, but would likely result in some confusion.

I could key the localStorage by both id AND submission, which would fix this issue. Then we'd just revert to `Your submission is in progress` and show no filename at all.

Thoughts?

**Comment by awolfe76** [comment]
We aren't explicitly sending it back, as you suggest, but the [back-end does have it](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#summary). We use that to render the summary information on the confirmation page. (And that page could cause even more confusion ... "I uploaded `x.txt` and the upload page says so, so why is the summary saying `y.txt`?")

So for this case, where 2 filers are working and overwriting each other, that endpoint could help.

**Comment by wpears** [comment]
Oh duh, it's in the Content-Disposition of the upload. It would be pretty keen to associate this filename with the submission then, if we're already using it elsewhere.

**Review by awolfe76 — APPROVED** [review]

**Pull request merged**
