### PR TITLE
Start of React and updates to build process

### PR DESCRIPTION
**Pull request by awolfe76**
### @wpears you can check this out but don't merge yet. will add readme updates and a test
- adds several build tasks (run `npm run watch` to have browser-sync work)
  - this PR is mostly dealing with the build, took a bit to get that working nicely
- creates basic form
  - only has file input and button
  - removed year (we will only be doing 1 at the start)
  - removed checkbox for performance increase

### CODE REVIEW

**Comment by wpears** [comment]
What's the 'removed checkbox for performance increase' part? Otherwise looks good for now

**Comment by awolfe76** [comment]
This part:
performance

**Comment by wpears** [comment]
Ahhh of course! I thought you were having performance problems because of a checkbox and I was quite concerned ;)

**Comment by awolfe76** [comment]
@wpears - this is good to go now ... hopefully.

**Comment by wpears** [comment]
Cool :+1:

**Pull request merged**
