### PR TITLE
Display all 0 values in the AUS tables as the phrase (blank)

### LINKED ISSUE #1286: Edits: AUS and AUS result values should be displayed as (Blank)
When there's nothing entered in the field, currently 0's are displayed. Instead of 0's, the message (Blank) should be displayed. 

image

### PR DESCRIPTION
**Pull request by PatrickGoRaft**
closes #1286

### CODE REVIEW

**Comment by wpears** [comment]
This doesn't actually solve the ticket, as the proposed change will change **ALL** `0`s to `(blank)` when the intent is to just do it for the AUS tables.

Personally I think anything involving the clarity of the content of the API response should be fixed at the API level since some institutions will want to file using just the API.

If that is unrealistic, the change on the frontend would likely consist of creating a list of AUS edits in an object (ie `{V696-1: 1,...}`) and checking presence in that list before returning `(blank)` when encountering a 0.

This will either have to be done at a higher level than `TableCell` (which doesn't know what the edit is) or the edit name will need to be passed down to `TableRow` and `TableCell`.

**Review by wpears — CHANGES_REQUESTED** [review]
(see above comment)

**Comment by PatrickGoRaft** [comment]
You are correct my good sir, I was just trying some thing's out between changing the front end and backend. I was going through the component hierarchy to implement what youre suggesting rather than tweaking the results of the API call. 

I was going to add a flag in the event a table header contained a column with a name AUS and pass this flag down to the cell component.

**Comment by PatrickGoRaft** [comment]
@wpears  I've implemented the changes we discussed ,since  `TableRow.jsx` contains the column name data via field.name I'm just passing that down to `TableCell.jsx`

**Review by wpears — APPROVED** [review]

**Pull request merged**
