### PR TITLE
No js

### LINKED ISSUE #841: No javascript
Like we do for older browsers, we could show a message if javascript is disabled.

### PR DESCRIPTION
**Pull request by awolfe76**
Closes #841 

If, for some reason, someone doesn't have javascript enabled this is what they will see.

I thought it would be nice to keep the idea of the header (no nav), some content (FAQs, disclaimers), and footer.

I could use some help with the content in the hero section though. For now, the heading tells them about needing javascript and I kept our intro paragraph. Any other ideas?

@wpears @designlanguage @keileyo

no-js

### CODE REVIEW

**Comment by keileyo** [comment]
I would suggest something like "Please enable javascript to use the HMDA Platform." in the header, and would add a sentence to the end of the intro paragraph restating that. 

"In order to use the HMDA Platform, javascript must be enabled."

**Comment by designlanguage** [comment]
@keileyo - That heading seems a bit long. How about using @awolfe76's heading, but using your additional sentence at the beginning of the intro paragraph:

### Please enable Javascript to continue
In order to use the HMDA Platform, Javascript must be enabled. Beginning with HMDA data collected...

**Comment by wpears** [comment]
I think @designlanguage 's wording makes sense. Implementation-wise I'm a little hesitant about duplicating much of the homepage's content in the noscript, but it's fine for now, especially since there won't be too much change to the homepage at this juncture.
  
Also, I added a bit of styling to fix some rendering of the analytics noscript iframe

**Comment by awolfe76** [comment]
@wpears - this should be good now. See 305a7f6 for the update.

And I agree about the content. Just didn't seem too bad at the moment.

**Comment by keileyo** [comment]
sounds good to me

**Comment by wpears** [comment]
:+1:

**Pull request merged**
