### PR TITLE
Remove macro justifications

### LINKED ISSUE #435: Change macro justification to a single checkbox
After https://github.com/cfpb/hmda-platform/issues/846 is complete, implement the single checkbox justification for macro edits.

### LINKED ISSUE #456: Clear signature state on reupload
If the filer has checked the signature checkbox, completed submission or not, the checkbox remains checked even after an upload.

The state for the signature checkbox should be `checked: false` in this case.

### PR DESCRIPTION
**Pull request by awolfe76**
~~_This is a WIP so I can give a quick demo but you can start a review. The state from the back-end doesn't seem to be updating correctly. AND it needs tests updated.~~_

Closes #435 

- removes the justifications for macro edits
- updates/adds/removes actions to update the state correctly, macro acts like quality

Closes #456 

- https://github.com/cfpb/hmda-platform-ui/commit/b40cb1b7e9377294e3273a092fb52bc667b3a0f8 resets signature state

### CODE REVIEW

**Comment by awolfe76** [comment]
@wpears - this should be good then, knowing that the back-end status doesn't get updated when all edits are verified.

**Comment by wpears** [comment]
This looks good, but I wanted to collapse a lot of the common code between quality/macro so I opened https://github.com/cfpb/hmda-platform-ui/pull/458 Give it some :eyes:

**Comment by awolfe76** [comment]
@wpears - 😃  I was going to create an issue for that but since you got it started I added your updates to this PR and did a bit more to create common code for the verifications.

**Comment by wpears** [comment]
💟

**Pull request merged**
