### PR TITLE
add the data scheme to csp to allow proper functioning of gtm

### LINKED ISSUE #861: Add data scheme for gtm

### PR DESCRIPTION
**Pull request by wpears**
Closes #861

### CODE REVIEW

**Comment by awolfe76** [comment]
@wpears - What was going on here? Did you see errors?

**Comment by wpears** [comment]
Yep, the gtm, redirect wasn't actually running.

**Comment by awolfe76** [comment]
Going to try this out tomorrow, but can you tell me what you were seeing exactly? Is there something I should be looking for?

_* I ask because there are __some__ `ffiec.cfpb.gov` and `192.168.99.100` (docker-compose build) analytics showing up in GA. I say __some__ because I think there should be more, but not sure._

**Comment by wpears** [comment]
screen shot 2017-11-02 at 9 18 00 am

**Comment by awolfe76** [comment]
Interesting. I haven't seen that. Did you see it locally? And every time?

I'll merge and keep an eye on GA to make sure it's still updating.

**Pull request merged**
