### PR TITLE
Give logo a hover state and an underline

### LINKED ISSUE #701: Make "HMDA filing" link look more actionable
Tests revealed that some people didn't realize they could click on "HMDA filing" to return to the home/institutions page.

For an attempted quick-fix, can we underline it and give it a rollover color?

We've also referred to this as the "HMDA Platform". Shouldn't we use that wording instead (@keileyo @lesgou)?

### PR DESCRIPTION
**Pull request by wpears**
Closes #701 
(with https://github.com/cfpb/hmda-platform-auth/pull/141 to stay consistent)

### CODE REVIEW

**Review by awolfe76 — CHANGES_REQUESTED** [review]
From #701 it looks like this should be updated to say `HMDA Platform`?

**Comment by awolfe76** [comment]
Also see [this comment](https://github.com/cfpb/hmda-platform-ui/issues/701#issuecomment-321587805). Seems like that might be an even better solution.

**Comment by wpears** [comment]
@awolfe76 Underline removed and homelink added

**Review by awolfe76 — APPROVED** [review]
It _might_ make more sense to have the home link to the left of the user/logout but lets give it a try and find out. 😄

**Pull request merged**
