### PR TITLE
No beta content

### LINKED ISSUE #935: Remove beta content
Go through the app and update content to remove all references to beta.

### PR DESCRIPTION
**Pull request by awolfe76**
Wait to merge until @keileyo, @designlanguage, and @colleenms have given the ok.
This PR can be reviewed at the link sent earlier.

Closes #935 

Goes with https://github.com/cfpb/hmda-platform-auth/pull/200.

### CODE REVIEW

**Comment by designlanguage** [comment]
This all looks good to to me. In SubmissionReceipt.jsx though, shouldn't it be "...completed your filing for __the__ {' '} {filingPeriod}!"

**Comment by awolfe76** [comment]
@designlanguage - adding that would make it read "completed your filing for the 2017!". `{filingPeriod}` here is just the year.

We _could_ say "completed your filing for the 2017 filing period!" if that sounds better.

**Comment by designlanguage** [comment]
Ah, okay, that makes sense. No, I think the way it is now works. Thanks!

**Comment by awolfe76** [comment]
@wpears - good to go here.

**Review by wpears — APPROVED** [review]
👍

**Pull request merged**
