### PR TITLE
RefileWarning update and parse error reword

### LINKED ISSUE #415: Backlog for now: Recommended update to ui - parsing error language
**Backlog for now**:

- [ ] Recommend updating the wording in the red banner to:
Your file has format errors. Update your file and select the "Update a new file" button, or return to the Institutions page.

image

- [ ] Recommend updating the error message to:
XX Formatting Errors
The uploaded file is not formatted according to the requirements specified in the [Filing Instructions Guide for data collected in 2017](https://www.consumerfinance.gov/data-research/hmda/static/for-filers/2017/2017-HMDA-FIG.pdf). Make corrections in your file and then upload your file **here**.

image

### LINKED ISSUE #474: Refile warnings
These could use a little attention:

warning-qual
warning-syn

The spacing seems off, the positioning of the refile button, some bold test on the syntactical and validity but not on the quality/macro.

Do we want to show the refile button so prominently on the quality/macro warning. We don't want to mislead the filer into thinking that's the only (or best) option for those edits.

### PR DESCRIPTION
**Pull request by wpears**
Closes #474 
Closes #415

### CODE REVIEW

**Comment by awolfe76** [comment]
@wpears - made a few changes here to make the content more consistent.

Would also like @lesgou and @keileyo to take a look. Here are some screenshots to help:

formatting

syntax

quality

macro

**Comment by lesgou** [comment]
Maybe consider user links instead of a button?

**Comment by wpears** [comment]
Now Closes #486

**Review by awolfe76 — APPROVED** [review]
👍

**Pull request merged**
